name: Publish Documentation

on:
    push:
        branches: [v6]

jobs:
    docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Enable Corepack
              run: corepack enable

            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: 20
                  cache: "yarn"

            - name: Install dependencies
              run: yarn install

            - name: Build
              run: yarn run docs

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                  branch: docs
                  folder: docs
